name: share_launcher
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  share_plus: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
