name: deep_link_client
description: A Dart package which provides a deep link stream
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_core: ^1.15.0
  firebase_dynamic_links: ^4.2.0
  rxdart: ^0.27.3
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d

dev_dependencies:
  firebase_core_platform_interface: ^4.2.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
