name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.3
  package_info_client:
    path: ../package_info_client

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^2.4.0
