name: analytics_repository
description: Package which manages the analytics domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  firebase_analytics: ^8.2.0
  flutter:
    sdk: flutter
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
