include: package:very_good_analysis/analysis_options.10.0.0.yaml
analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - lib/l10n/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
