name: flutter_news_example
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  ads_consent_client:
    path: packages/ads_consent_client
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  article_repository:
    path: packages/article_repository
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  clock: ^1.1.1
  collection: ^1.17.1
  deep_link_client:
    path: packages/deep_link_client
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.5
  firebase_analytics: ^10.4.3
  firebase_auth_platform_interface: ^6.15.3
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_dynamic_links: ^5.3.3
  firebase_messaging: ^14.6.3
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_news_example_api:
    path: api
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  form_inputs:
    path: packages/form_inputs
  google_mobile_ads: ^2.4.0
  hydrated_bloc: ^9.1.2
  in_app_purchase_repository:
    path: packages/in_app_purchase_repository
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mockingjay: ^0.3.0
  news_blocks:
    path: api/packages/news_blocks
  news_blocks_ui:
    path: packages/news_blocks_ui
  news_repository:
    path: packages/news_repository
  notifications_repository:
    path: packages/notifications_repository
  package_info_client:
    path: packages/package_info_client
  path_provider: ^2.0.15
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  platform: ^3.1.0
  purchase_client:
    path: packages/purchase_client
  share_launcher:
    path: packages/share_launcher
  shared_preferences: ^2.1.2
  sliver_tools: ^0.2.10
  stream_transform: ^2.1.0
  test: ^1.24.1
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.1.11
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^5.0.0+1
  video_player_platform_interface: ^6.1.0
  visibility_detector: ^0.3.3

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  build_verify: ^3.1.0
  build_version: ^2.1.1
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1

flutter:
  generate: true
  uses-material-design: true
