name: storage
description: A Key/Value Storage Client for Dart.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d
