name: gallery
description: Gallery project to showcase app_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_ui:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d

flutter:
  uses-material-design: true
