name: in_app_purchase_repository
description: A repository that manages user purchase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_news_example_api:
    path: ../../api
  in_app_purchase: ^3.1.7

dev_dependencies:
  coverage: ^1.6.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.24.1
  very_good_analysis: ^5.0.0+1
