name: news_repository
description: A repository that exposes news data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter_news_example_api:
    path: ../../api

dev_dependencies:
  coverage: ^1.6.3
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
