name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.0
  google_sign_in: ^5.0.5
  sign_in_with_apple: ^4.1.0
  token_storage:
    path: ../token_storage
  twitter_login: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
