name: news_repository
description: A repository that exposes news data.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  google_news_template_api:
    path: ../../api
  news_blocks:
    path: ../../api/packages/news_blocks

dev_dependencies:
  coverage: ^1.2.0
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d
