include: package:very_good_analysis/analysis_options.10.0.0.yaml
analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - build/**
    - lib/**/*.g.dart
    - packages/**/*.gen.dart
    
linter:
  rules:
    file_names: false
