name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  formz: ^0.5.0-dev.1

dev_dependencies:
  test: ^1.16.4
  very_good_analysis:
    git:
      url: https://github.com/verygoodopensource/very_good_analysis
      ref: 9f26d3479ce9eff910a7cf79585ffafc6211c87d
