name: deep_link_client
description: A Dart package which provides a deep link stream
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.3
  plugin_platform_interface: ^2.1.4
  rxdart: ^0.27.7
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
