name: google_news_template_api
description: A Google News Template server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  dart_frog: ^0.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.6.0
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.1.0
