name: news_blocks_ui
description: A Flutter package that contains UI components for news blocks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_ui:
    path: ../app_ui
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  google_mobile_ads: ^2.4.0
  news_blocks:
    path: ../../api/packages/news_blocks
  path_provider_platform_interface: ^2.0.6
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.4
  url_launcher: ^6.1.11
  url_launcher_platform_interface: ^2.1.3
  video_player: ^2.6.1
  video_player_platform_interface: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.5
  fake_async: ^1.3.1
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
