name: deep_link_client
description: A deep link client interface
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.5

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
