name: package_info_client
description: A client that provides current device information like OS
  version or device model
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
