name: notification_preferences_repository
description: A repository that manages notification preferences.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  news_blocks:
    path: ../../api/packages/news_blocks
  persistent_storage:
    path: ../storage/persistent_storage

dev_dependencies:
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
