name: firebase_authentication_client
description: A Firebase implementation of the authentication client interface
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_client:
    path: ../authentication_client
  firebase_auth: ^4.6.3
  firebase_auth_platform_interface: ^6.15.3
  firebase_core: ^2.14.0
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.1.4
  plugin_platform_interface: ^2.1.4
  sign_in_with_apple: ^5.0.0
  token_storage:
    path: ../token_storage
  twitter_login: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
