name: google_news_template_api
description: A server app using the shelf package and Docker.
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  news_blocks:
    path: packages/news_blocks
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  meta: ^1.7.0
  mocktail: ^0.3.0
  test: ^1.15.0
  test_process: ^2.0.0
  very_good_analysis: ^2.4.0
