name: google_news_template_api
description: A server app using the shelf package and Docker.
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  test: ^1.15.0
  test_process: ^2.0.0
  very_good_analysis: ^2.4.0
