name: generate_flutter_news_template

on:
  push:
    paths:
      - tool/generator/**
      - flutter_news_example/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        working-directory: tool/generator
        run: dart pub get

      - name: Generate Template
        run: dart ./tool/generator/main.dart

      - name: Stash Changes
        run: git stash

      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: templates

      - name: Clean Template
        run: git rm -r --ignore-unmatch flutter_news_template/__brick__

      - name: Unstash Changes
        run: git stash pop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          branch: chore/generate-flutter-news-template
          commit-message: "chore: generate flutter_news_template"
          title: "chore: generate flutter_news_template"
          body: Please squash and merge me!
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: felangel
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
