name: news_blocks_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "flutter_news_example/packages/news_blocks_ui/**"
      - ".github/workflows/news_blocks_ui.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.16.9
      working_directory: flutter_news_example/packages/news_blocks_ui
      coverage_excludes: "lib/src/generated/*.dart"
      # Due to incompability with custom goldenFileComparator,
      # reference: flutter_news_example/packages/news_blocks_ui/test/helpers/tolerant_comparator.dart
      test_optimization: false
