name: token_storage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "google_news_project/packages/authentication_client/token_storage/**"
      - ".github/workflows/token_storage.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: google_news_project/packages/authentication_client/token_storage
