name: {{project_name.snakeCase()}}
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: {{flutter_version}}

dependencies:
  ads_consent_client:
    path: packages/ads_consent_client
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  article_repository:
    path: packages/article_repository
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  clock: ^1.1.1
  collection: ^1.19.0
  deep_link_client:
    path: packages/deep_link_client/deep_link_client
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.3
  firebase_analytics: ^11.3.6
  firebase_auth_platform_interface: ^7.7.1
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.8
  firebase_deep_link_client:
    path: packages/deep_link_client/firebase_deep_link_client
  firebase_dynamic_links: ^6.1.8
  firebase_messaging: ^15.2.8
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  {{project_name.snakeCase()}}_api:
    path: api
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.1
  form_inputs:
    path: packages/form_inputs
  google_mobile_ads: ^5.3.1
  hydrated_bloc: ^10.1.1
  in_app_purchase_repository:
    path: packages/in_app_purchase_repository
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockingjay: ^0.6.0
  news_blocks:
    path: api/packages/news_blocks
  news_blocks_ui:
    path: packages/news_blocks_ui
  news_repository:
    path: packages/news_repository
  notifications_repository:
    path: packages/notifications_repository
  package_info_client:
    path: packages/package_info_client
  path_provider: ^2.1.5
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  platform: ^3.1.6
  purchase_client:
    path: packages/purchase_client
  share_launcher:
    path: packages/share_launcher
  shared_preferences: ^2.5.3
  sliver_tools: ^0.2.9
  stream_transform: ^2.1.1
  test: ^1.21.4
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.3.2
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^7.0.0
  video_player_platform_interface: ^6.4.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.1
  build_version: ^2.1.1
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.2
  mocktail_image_network: ^1.2.0

dependency_overrides:
  intl: ^0.19.0
  win32: ^5.5.4

flutter:
  generate: true
  uses-material-design: true
